/**
 * Monorepo-wide ESLint configuration.
 *
 * `@sorrell/eslint-config` is a flat config (ESLint 9): it already carries
 * its `plugins` (as objects), `files` globs, `extends`, and rules, so it is
 * spread straight into `defineConfig`.  It must *not* be passed through
 * `FlatCompat` — that bridge is only for legacy, eslintrc-shaped configs, and
 * handing it flat plugin objects (whose `@typescript-eslint` entry is a
 * circular graph) crashes ESLint while it tries to JSON-serialize them for
 * schema validation ("Converting circular structure to JSON").
 *
 * @file      eslint.config.js
 * @author    Gage Sorrell <gage@sorrell.sh>
 * @copyright (c) 2026 Gage Sorrell
 * @license   MIT
 */

import ExpoConfig from "eslint-config-expo/flat.js";
import ReactPerf  from "eslint-plugin-react-perf";
import SorrellConfig from "@sorrell/eslint-config";
import { defineConfig } from "eslint/config";

export default defineConfig(
    ExpoConfig,
    SorrellConfig,
    {
        files: [ "**/Application/**/*.js" ],
        rules:
        {
            "@typescript-eslint/typedef": "off"
        }
    },
    {
        /* Next.js build output — never hand-authored, and picking it up
           crashes some jsdoc rules on the minified/bundled JS inside it. */
        ignores: [ "**/.next/**" ]
    },
    {
        /* ESLint ignores dot-directories by default (`.rnstorybook`,
           `.expo`, ...). `.rnstorybook/stories/*` and its `main.ts`/
           `preview.tsx` are hand-written source, not generated output, so
           un-ignore them; `storybook.requires.ts` (auto-generated by
           Storybook itself — "do not edit") stays ignored. */
        ignores: [ "!**/.rnstorybook/**" ]
    },
    {
        ignores: [ "**/.rnstorybook/storybook.requires.ts" ]
    },
    {
        /* Storybook story files are demo/config code, not documented API
           surface, so don't require JSDoc blocks on their exports. */
        files: [ "**/*.stories.tsx" ],
        rules:
        {
            "jsdoc/require-jsdoc": "off"
        }
    },
    {
        /* shadcn/ui primitives are generated/vendored via the shadcn CLI,
           not hand-authored documented API surface, so don't hold them to
           the file-header/JSDoc conventions the rest of the repo follows.
           The leading globstar keeps this pattern matching whether ESLint
           resolves `files` globs relative to the repo root
           (`Configuration/eslint.config.js` run directly) or relative to
           `Website` (via that workspace's own `eslint.config.js`
           re-export). */
        files: [ "**/components/ui/**/*.tsx" ],
        rules:
        {
            "jsdoc/require-jsdoc": "off",
            "jsdoc/require-file-overview": "off",
            "jsdoc/require-description": "off",
            "jsdoc/no-blank-blocks": "off",
            "sort-imports": "off",
            "@stylistic/jsx-max-props-per-line": "off",
            "@stylistic/max-len": "off",
            "@typescript-eslint/naming-convention": "off"
        }
    },
    {
        /* Next.js writes and rewrites this file itself on every build/dev
           run — nothing here is hand-authored. */
        ignores: [ "**/next-env.d.ts" ]
    },
    {
        rules:
        {
            "@sorrell/jsdoc-file-name": "error",
            "@typescript-eslint/no-require-imports": "off",
            "jsdoc/no-blank-block-descriptions": "off",
            "jsdoc/sort-tags":
            [
                "error",
                {
                    reportIntraTagGroupSpacing: false,
                    reportTagGroupSpacing: false,
                    tagSequence:
                    [
                        {
                            tags:
                            [
                                "module",
                                "internal",
                                "file",
                                "author",
                                "copyright",
                                "license"
                            ]
                        }
                    ]
                }
            ]
        }
    },
    {
        plugins:
        {
            "react-perf": ReactPerf
        },
        rules:
        {
            "react-perf/jsx-no-new-object-as-prop": "warn",
            "react-perf/jsx-no-new-array-as-prop": "warn",
            "react-perf/jsx-no-new-function-as-prop": "warn",
        }
    },
    {
        files: [ "**/Application/**/*.js", "**/Application/**/*.stories.tsx" ],
        rules:
        {
            "@typescript-eslint/typedef": "off",
            "jsdoc/require-jsdoc": "off"
        }
    }
);
